### ISSUE TITLE
Incredible idea but why no iOS sdk?

### ISSUE THREAD

**Issue by jsoneaday** [solana-mobile/solana-mobile-stack-sdk#6]

**Comment by robbestad** [comment]
Did you read the README?

**Comment by jsoneaday** [comment]
I see. Any eta on ios support?

**Comment by sdlaver** [comment]
The Mobile Wallet Adapter spec envisions iOS support, but nothing to announce at the moment. The #sdk channel on Discord will be the place to find out about development plans for SMS.
