### ISSUE TITLE
Solana Saga and other ecosystems?

### ISSUE THREAD

**Issue by darko-mijic** [solana-mobile/solana-mobile-stack-sdk#9]
Are the Solana Saga phone and Solana Mobile Stack intended to be used only with the Solana network, or are there plans to support other ecosystems in the future that would like to integrate with the Solana Saga phone and build apps for it? A mobile phone as a hardware wallet and a decentralized app store would be a massive win for the whole crypto ecosystem.

**Comment by sdlaver** [comment]
We started with Solana, because we believe it is the best blockchain for mobile (speed, cost, and scalability). We do want to add support for other chains into the core SMS technologies (e.g. Seed Vault, Mobile Wallet Adapter), but we haven't announced any roadmap for such support at this time.
